# Generated by Django 4.2.9 on 2024-01-11 19:22

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='London', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
