# Generated by Django 4.2.9 on 2024-01-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comments_options_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('goods_products', models.BooleanField(default=False)),
                ('foods_products', models.BooleanField(default=False)),
                ('time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
